name: systematicity_venv
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - numpy=1.26.4=py39h3b2db8e_0
  - numpy-base=1.26.4=py39ha9811e2_0
  - pandas=2.2.1=py39h313beb8_0
  - python=3.9.16=hea58f1e_0_cpython
  - matplotlib=3.8.4=py39hca03da5_0
  - matplotlib-base=3.8.4=py39h46d7db6_0
  - seaborn=0.12.2=py39hca03da5_0
  - scikit-image=0.22.0=py39h46d7db6_0
  - scikit-learn=1.3.0=py39h46d7db6_1
  - scipy=1.12.0=py39h20cbe94_0
  - networkx=3.1=py39hca03da5_0
  - ipykernel=6.28.0=py39hca03da5_0
  - ipython=8.15.0=py39hca03da5_0
  - tqdm=4.65.0=py39h86d0a89_0
  - pygraphviz=1.9=py39h961d116_0
  - regex=2024.7.24=py39h80987f9_0
  - pygraphviz=1.9=py39h961d116_0
  - pip=24.2
  - pip:
      - argparse==1.4.0
      - colormath==3.0.0
      - cryptography==42.0.8
      - cython==3.0.11
      - einops==0.8.0 
      - openpyxl==3.1.5
      - pip==24.2
      - rtree==1.3.0
      - setuptools==74.0.0
      - termcolor==2.4.0
      - tsv==1.2
      - unidecode==1.3.8
prefix: /opt/miniconda3/envs/systematicity_venv
